---
unitClasses:
  - id: aw_fire
    name: structure_aw_fire
    cost: 500
    movement: land_building
    moveRange: 0
    damageMultiplier: 1
    aiPriority: -1.0
    tags:
      - aw_fire
      - structure
    battleUnitCount: 1
    passiveMultiplier: 1.0
    sightRange: 3
    isStructure: true
    isNeutraliseable: false
    canBeCaptured: false
    canReinforce: false
    canBeReinforced: false
    regeneration: 10
    scout: true


units:
  - class: aw_fire
    faction: neutral
    grabPos: [16, 24]
    mapAnimation: units/structures/awfire/aw_fire
    mediumPortrait: portraits/structures/medium/aw_fire.png
    name: structure_aw_fire
    smallPortrait: portraits/structures/small/aw_fire.png
    sounds:
      death: gateDie
      hit: hitWood
      hitMap: hitStone
    structureImage:
      farBackground: aw_fire_background_000_0_0
      foreground: aw_fire_background_000_0_0
      keeperPosition:
      - 0
      - 0
      leftBannerOffset:
      - 0
      - 0
      nearBackground: aw_fire_background_000_0_0
      rightBannerOffset:
      - 0
      - 0
      spriteSheet: background_aw_fire

...
